name: Terraform CI/CD Pipeline
on:
  push:
    branches: [main]
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout 
        uses: actions/checkout@v3
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.5
      
      - name: Terraform Init & Plan
        working-directory: ./iac/terraform
        run: | 
          terraform init
          terraform import aws_ecr_repository.tutoragent_ecr_repository tutoragent_ecr_repository || true
          terraform import aws_iam_role.ecsTaskExecutionRole ecsTaskExecutionRole || true
          terraform import aws_iam_role_policy_attachment.ecsTaskExecutionRole_policy ecsTaskExecutionRole/arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy || true
          terraform import aws_ecs_cluster.ecs-cluster-one ecs-cluster-one || true
          terraform import aws_ecs_service.tutoragent-service ecs-cluster-one/tutoragent-service || true  
          SG_ID=$(aws ec2 describe-security-groups --region ap-south-1 --filters Name=group-name,Values=tutoragent-sg --query "SecurityGroups[0].GroupId" --output text)
          if [ "$SG_ID" != "None" ] && [ -n "$SG_ID" ]; then terraform import aws_security_group.tutoragent-sg $SG_ID || true; fi
          terraform import aws_ecs_task_definition.tutoragent-task-definition tutoragent-task || true
          sleep 15
          terraform plan -out=tfplan-output.json
      
      # Format check to ensure standard style compliance 
      - name: Terraform Format Check
        working-directory: ./iac/terraform
        run: terraform fmt -check

      # Validate the configuration code for structural syntax errors
      - name: Terraform Validate
        working-directory: ./iac/terraform
        run: terraform validate

      # Execute the changes automatically without interactive prompts
      - name: Terraform Apply
        working-directory: ./iac/terraform
        run: terraform apply -auto-approve tfplan-output.json

      - name: Terraform output ECS TASK Definition
        working-directory: ./iac/terraform
        run: | 
          terraform output -raw ecs_task_definition_json > tutoragent-task-definition.json
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tutoragent-task-definition.json
          path: ./iac/terraform/tutoragent-task-definition.json